### PR TITLE
Better handle duplicate letter comparison

### PR DESCRIPTION
**Pull request by BE-Code**
update guess_word function to properly handle duplicate letters

### CODE REVIEW

**Comment by exciteabletom** [comment]
Hi Bradley,
Thanks so much for the PR, that is a really clever solution! I will merge this right away.

**Comment by BE-Code** [comment]
You're welcome! Thanks for making this great project! Do you have any tutorials you would recommend for making a flask/Vue.js project like this from scratch? It's really cool.

**Comment by exciteabletom** [comment]
The documentation on the official Flask and Vue sites is amazing! I would start with a simple Flask app first, then add the Vue frontend. You obviously have a good grasp of Python so Flask should be very easy for you. 

Also, if you struggle with motivation, create something that you personally find useful or interesting. Maybe ask friends if there are sites they wish existed that you could make. 

It can be difficult to stick with it if you are following a boring tutorial with no relevance to your interests.

Best of luck :)

**Comment by BE-Code** [comment]
Thank you!

**Pull request merged**
